language: c
script:
  - bin/list-all
  - asdf plugin-add sbt ./
  - asdf list-all sbt
  - asdf plugin-test sbt https://github.com/lerencao/asdf-sbt.git
before_script:
  - git clone https://github.com/asdf-vm/asdf.git --branch v0.4.3
  - . asdf/asdf.sh
os:
  - linux
  - osx
